# language: zh-TW
# Generated by sa-expert
# Source: pm/audit-log.feature
# Project scan date: 2026-03-04

Feature: 稽核日誌（Audit Log）
  對應模組：src/audit/AuditLogger.ts
  相關類別：IAuditLogger, AuditLogger
  資料型別：AuditLogEntry (src/types/audit.ts)
  依賴套件：pino（結構化日誌輸出）

  Background:
    Given MCPServer 已啟動
    And ServerConfig.audit.enabled = true
    And AuditLogger 已初始化，底層使用 pino logger

  Scenario: SQL 查詢成功後自動寫入稽核日誌
    Given AI Client 對連線 "sales-db" 成功執行 SQL 查詢 "SELECT * FROM orders"
    And 查詢回傳 100 筆結果，耗時 120ms
    When QueryDatabaseTool.execute() 完成查詢後呼叫 AuditLogger.log(entry)
    Then AuditLogger 寫入 AuditLogEntry，包含：
      | 欄位             | 值                       | 型別   |
      | timestamp        | (ISO 8601 格式)          | string |
      | connection_name  | sales-db                 | string |
      | query            | SELECT * FROM orders     | string |
      | row_count        | 100                      | number |
      | execution_time   | 120ms                    | string |
      | client           | (MCP client 識別資訊)    | string |
    And 日誌以結構化 JSON 格式輸出至 pino logger

  Scenario: MongoDB 查詢成功後自動寫入稽核日誌
    Given AI Client 對 MongoDB 連線 "mongo-db" 成功執行查詢
    When MongoDBQueryTool.execute() 完成查詢後呼叫 AuditLogger.log(entry)
    Then AuditLogger 寫入 AuditLogEntry，包含 timestamp、connection_name、query、row_count、execution_time、client

  Scenario: 稽核日誌功能停用時不記錄
    Given ServerConfig.audit.enabled = false
    When 任意 Tool 呼叫 AuditLogger.log(entry)
    Then AuditLogger 檢查 audit.enabled 為 false
    And 不執行任何日誌寫入操作（early return）

  Scenario: STDIO MCP 模式下仍記錄稽核日誌
    Given MCPServer 以 STDIO 模式啟動（StdioTransport）
    And ServerConfig.audit.enabled = true
    When AI Client 透過 MCP Protocol 執行查詢
    Then AuditLogger.log() 仍正常寫入稽核日誌
    And 稽核日誌輸出至 stderr 或獨立日誌檔案（避免干擾 STDIO 的 stdout 通道）
