# language: zh-TW
# Generated by sa-expert
# Source: pm/connection-management.feature
# Project scan date: 2026-03-04

Feature: 連線管理（Connection Management）
  對應模組：src/database/pool/ConnectionManager.ts, src/config/ConfigLoader.ts
  相關類別：ConnectionManager, ConnectionPool, ConfigLoader, DriverFactory
  資料型別：ConnectionConfig, PoolConfig, ConnectionCapabilities (src/types/connection.ts)

  Background:
    Given 系統已載入 YAML 設定檔，ConfigLoader.loadConfig() 回傳 ServerConfig，其中 connections 包含：
      | name     | type  | host      | port | database | aliases          |
      | sales-db | mssql | 10.0.0.10 | 1433 | sales    | prod_sales_ro    |
    And ServerConfig.pool 設定為 { max: 10, min: 2, idleTimeout: 30000 }
    And ServerConfig.limits 設定為 { max_rows: 1000, timeout: 30, result_size: 5, max_execution_time: 60 }

  Scenario: 成功列出所有資料庫連線
    Given MCPServer 已啟動且 ToolRegistry 已註冊所有 Tools
    When AI Client 呼叫 MCP Tool "list_connections"（無參數）
    Then ListConnectionsTool.execute() 呼叫 ConnectionManager.listConnections()
    And 回傳 ConnectionInfo[] 陣列，每筆包含：
      | 欄位     | 型別   | 說明            |
      | name     | string | 連線名稱        |
      | type     | string | 資料庫類型      |
      | host     | string | 主機位址        |
      | port     | number | 連接埠          |
      | database | string | 資料庫名稱      |

  Scenario: 系統啟動時自動建立連線池
    Given ConfigLoader.loadConfig() 已回傳 ServerConfig
    And ServerConfig.pool = { max: 10, min: 2, idleTimeout: 30000 }
    When ConnectionManager.createPools(connections, poolConfig) 被呼叫
    Then 為每個 ConnectionConfig 建立獨立的 ConnectionPool 實例
    And 每個 ConnectionPool 透過 DriverFactory.createDriver(type) 取得對應的 IDriverAdapter
    And ConnectionPool 以 { max: 10, min: 2, idleTimeout: 30000 } 初始化

  Scenario: 連線池閒置超時自動銷毀
    Given ConnectionPool 已建立，idleTimeout 設定為 30000 毫秒
    When ConnectionPool 閒置時間超過 30000 毫秒（無任何查詢活動）
    Then ConnectionPool 自動呼叫 destroy() 釋放所有連線資源
    And ConnectionManager 將該 pool 從活躍池清單中移除

  Scenario: 設定檔載入成功
    Given YAML 設定檔路徑有效且格式正確
    When ConfigLoader.loadConfig(yamlPath) 被呼叫
    Then 回傳 ServerConfig 物件，包含：
      | 屬性         | 型別              |
      | connections  | ConnectionConfig[] |
      | pool         | PoolConfig        |
      | limits       | LimitsConfig      |
      | audit        | AuditConfig       |
    And ConfigValidator.validate(config) 驗證所有必填欄位存在

  Scenario: 使用 connection_name 指定查詢連線
    Given ConnectionManager 已建立 "sales-db" 的 ConnectionPool
    When 任意 Tool 呼叫 ConnectionManager.resolveConnection("sales-db")
    Then ConnectionManager 直接比對 name 欄位，回傳 "sales-db" 對應的 IDriverAdapter

  Scenario: 使用 alias 指定查詢連線
    Given ConnectionConfig "sales-db" 設定了 aliases: ["prod_sales_ro"]
    When 任意 Tool 呼叫 ConnectionManager.resolveConnection("prod_sales_ro")
    Then ConnectionManager 將 alias "prod_sales_ro" 解析為 "sales-db"
    And 回傳 "sales-db" 對應的 IDriverAdapter

  Scenario: 未傳入 connection_name 時拒絕請求
    Given ServerConfig.default_connection 未設定（undefined）
    When AI Client 呼叫任意查詢 Tool 但未傳入 connection_name 參數
    Then Tool 回傳錯誤，訊息包含 "connection_name is required"
    And 不執行任何資料庫操作

  Scenario: dev 環境使用 default_connection
    Given ServerConfig.default_connection = "sales-db"
    When AI Client 呼叫任意查詢 Tool 但未傳入 connection_name 參數
    Then Tool 自動使用 "sales-db" 作為 connection_name
    And ConnectionManager.resolveConnection("sales-db") 被呼叫

  Scenario: 查詢連線能力（capabilities）
    Given ConnectionManager 已建立 "sales-db" 的 ConnectionPool
    When AI Client 查詢連線 "sales-db" 的 capabilities
    Then 回傳 ConnectionCapabilities 物件，包含：
      | 欄位           | 型別     | 說明                           |
      | supportedTools | string[] | 該連線支援的 tool 名稱清單     |
      | readOnly       | boolean  | 是否為唯讀模式（預設 true）    |
      | maxRows        | number   | 該連線的最大回傳行數           |
      | allowedSchemas | string[] | 允許查詢的 schema 清單         |

  Scenario: 使用者傳入的 limit 受 server 上限夾制
    Given ServerConfig.limits.max_rows = 1000
    When AI Client 呼叫查詢 Tool 並傳入 limit = 5000
    Then QueryPolicy.clampLimits() 將實際 limit 設為 Math.min(5000, 1000) = 1000
    And 查詢以 limit = 1000 執行

  Scenario: 使用者傳入的 timeout_ms 受 server 上限夾制
    Given ServerConfig.limits.timeout = 30（秒），即 30000 毫秒
    When AI Client 呼叫查詢 Tool 並傳入 timeout_ms = 60000
    Then QueryPolicy.clampLimits() 將實際 timeout_ms 設為 Math.min(60000, 30000) = 30000
    And 查詢以 timeout_ms = 30000 執行
