# language: zh-TW
# Generated by sa-expert
# Source: pm/credential-management.feature
# Project scan date: 2026-03-04

Feature: Credential 加密管理（Credential Management）
  對應模組：src/credential/
  相關類別：ICredentialProvider, CredentialResolver, EnvCredentialProvider, KeychainCredentialProvider, VaultCredentialProvider, AESCredentialProvider
  依賴套件：dotenv（.env 支援）、keytar（OS Keychain）

  # === Layer A：環境變數 / .env（預設） ===

  Scenario: 使用環境變數引用解析密碼（預設方式）
    Given YAML 設定檔中 ConnectionConfig.passwordRef = "${MSSQL_PASSWORD}"
    And ServerConfig.credential.provider = "env"（預設）
    And 環境變數 MSSQL_PASSWORD 已設定為有效值
    When CredentialResolver.resolve(passwordRef) 被呼叫
    Then CredentialResolver 選擇 EnvCredentialProvider
    And EnvCredentialProvider.resolve("MSSQL_PASSWORD") 讀取 process.env.MSSQL_PASSWORD
    And 回傳 { resolved: true, password: "(環境變數的值)" }
    And ConnectionManager 使用解析後的密碼建立資料庫連線

  Scenario: 環境變數未設定時解析失敗
    Given YAML 設定檔中 ConnectionConfig.passwordRef = "${MSSQL_PASSWORD}"
    And 環境變數 MSSQL_PASSWORD 未設定（undefined）
    When CredentialResolver.resolve(passwordRef) 被呼叫
    Then EnvCredentialProvider.resolve("MSSQL_PASSWORD") 回傳 undefined
    And CredentialResolver 回傳 { resolved: false, error: "Environment variable MSSQL_PASSWORD is not set" }
    And 系統啟動中止或跳過該連線

  Scenario: 使用 .env 檔案載入環境變數
    Given 專案目錄下存在 .env 檔案，包含 "MSSQL_PASSWORD=secret123"
    And YAML 設定檔中 ConnectionConfig.passwordRef = "${MSSQL_PASSWORD}"
    When 系統啟動時 ConfigLoader 呼叫 dotenv.config() 載入 .env
    And CredentialResolver.resolve(passwordRef) 被呼叫
    Then process.env.MSSQL_PASSWORD 已被 dotenv 設定
    And EnvCredentialProvider 成功取得密碼

  # === Layer B：本機加密（可選） ===

  Scenario: 使用 OS keychain 解析密碼
    Given ServerConfig.credential.provider = "keychain"
    And OS Keychain 中已儲存 service="mcp-database-server", account="sales-db" 的密碼
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then CredentialResolver 選擇 KeychainCredentialProvider
    And KeychainCredentialProvider.resolve("sales-db") 呼叫 keytar.getPassword("mcp-database-server", "sales-db")
    And 回傳 { resolved: true, password: "(keychain 中的值)" }

  Scenario: OS keychain 中找不到密碼時解析失敗
    Given ServerConfig.credential.provider = "keychain"
    And OS Keychain 中未儲存 "sales-db" 的密碼
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then KeychainCredentialProvider.resolve("sales-db") 回傳 null
    And CredentialResolver 回傳 { resolved: false, error: "Password for 'sales-db' not found in OS keychain" }

  # === Layer C：外部 Vault（企業選配） ===

  Scenario: 使用 HashiCorp Vault 解析密碼
    Given ServerConfig.credential.provider = "vault"
    And ServerConfig.credential.vault_url = "https://vault.example.com"
    And Vault 路徑 "secret/data/mcp/sales-db" 存在密碼
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then VaultCredentialProvider.resolve("sales-db") 呼叫 HTTP GET vault_url/v1/secret/data/mcp/sales-db
    And 回傳 { resolved: true, password: "(Vault 中的值)" }

  Scenario: 使用 AWS Secrets Manager 解析密碼
    Given ServerConfig.credential.provider = "vault"
    And ServerConfig.credential.vault_type = "aws-secrets-manager"
    And AWS Secrets Manager 中已儲存 secret name "mcp/sales-db"
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then VaultCredentialProvider.resolve("sales-db") 呼叫 AWS SDK GetSecretValue
    And 回傳 { resolved: true, password: "(AWS SM 中的值)" }

  Scenario: 使用 Azure Key Vault 解析密碼
    Given ServerConfig.credential.provider = "vault"
    And ServerConfig.credential.vault_type = "azure-key-vault"
    And Azure Key Vault 中已儲存 secret "mcp-sales-db"
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then VaultCredentialProvider.resolve("sales-db") 呼叫 Azure SDK getSecret
    And 回傳 { resolved: true, password: "(Azure KV 中的值)" }

  Scenario: 外部 Vault 無法連線時解析失敗
    Given ServerConfig.credential.provider = "vault"
    And Vault 服務無法連線（network error / timeout）
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then VaultCredentialProvider.resolve("sales-db") 拋出連線錯誤
    And CredentialResolver 回傳 { resolved: false, error: "Failed to connect to vault service: <error_message>" }

  # === Secret Provider Plugin Interface ===

  Scenario: 透過可插拔 Secret Provider 介面擴充
    Given 使用者實作了自訂的 ICredentialProvider，並透過 plugin 機制註冊
    And ServerConfig.credential.provider = "custom-plugin"
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then CredentialResolver 載入自訂 plugin 並呼叫其 resolve() 方法
    And 回傳 plugin 提供的密碼

  # === AES 檔案加密（不建議作為第一選項） ===

  Scenario: 使用 AES 加密檔案解析密碼
    Given ServerConfig.credential.provider = "aes"
    And ServerConfig.credential.aes_key_env = "MCP_MASTER_KEY"
    And 環境變數 MCP_MASTER_KEY 已設定（AES-256 master key）
    And 加密檔案中已儲存連線 "sales-db" 的密碼（AES-256-GCM 加密）
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then AESCredentialProvider.resolve("sales-db") 從環境變數取得 master key
    And 使用 master key 解密檔案，取得 "sales-db" 的密碼
    And 回傳 { resolved: true, password: "(解密後的值)" }

  Scenario: AES 加密的 master key 未設定時解析失敗
    Given ServerConfig.credential.provider = "aes"
    And ServerConfig.credential.aes_key_env = "MCP_MASTER_KEY"
    And 環境變數 MCP_MASTER_KEY 未設定
    When CredentialResolver.resolve("sales-db") 被呼叫
    Then AESCredentialProvider 偵測到 master key 環境變數缺失
    And 回傳 { resolved: false, error: "Master key environment variable MCP_MASTER_KEY is not set" }

  # === 安全規範 ===

  Scenario: YAML 設定檔禁止明文存放密碼
    Given YAML 設定檔中 password 欄位直接寫入明文 "plaintext123"（非 ${...} 格式）
    When ConfigLoader.loadConfig() 載入設定檔
    Then ConfigValidator.validate() 偵測到 password 欄位為明文
    And 系統回傳安全警告："Plaintext password detected in config. Use ${ENV_VAR} syntax or a credential provider."
    And 系統建議使用環境變數引用語法 "${...}" 或其他加密方式
