# language: zh-TW
# Generated by sa-expert
# Source: pm/http-authentication.feature
# Project scan date: 2026-03-04

Feature: HTTP 模式認證機制（HTTP Authentication）
  對應模組：src/auth/ApiKeyAuthenticator.ts, src/auth/RateLimiter.ts, src/auth/CorsHandler.ts
  相關類別：IAuthenticator, ApiKeyAuthenticator, JwtAuthenticator, RateLimiter, CorsHandler
  中介層位置：HttpTransport middleware chain

  Background:
    Given MCPServer 以 HTTP 模式啟動（HttpTransport）
    And ServerConfig.http.api_keys 包含至少一組有效 API Key
    And HttpTransport 的 middleware chain 順序為：CorsHandler -> RateLimiter -> Authenticator -> MCP Handler

  # === API Key 認證（預設支援） ===

  Scenario: API Key 認證成功
    When 客戶端發送 HTTP 請求，header 包含 "Authorization: Bearer valid-api-key"
    Then ApiKeyAuthenticator.authenticate(req) 提取 Bearer token
    And 比對 token 與 ServerConfig.http.api_keys 陣列
    And token 存在於 api_keys 中，驗證通過
    And 請求繼續進入 MCP Handler 處理

  Scenario: API Key 認證失敗 - 缺少 Authorization header
    When 客戶端發送 HTTP 請求但未包含 Authorization header
    Then ApiKeyAuthenticator.authenticate(req) 偵測到 header 缺失
    And 回傳 HTTP 401 Unauthorized，body 包含 { error: "Authorization header is required" }

  Scenario: API Key 認證失敗 - 無效的 API Key
    When 客戶端發送 HTTP 請求，header 包含 "Authorization: Bearer invalid-api-key"
    Then ApiKeyAuthenticator.authenticate(req) 比對 token 不在 api_keys 中
    And 回傳 HTTP 401 Unauthorized，body 包含 { error: "Invalid API key" }

  Scenario: API Key 認證失敗 - 格式錯誤的 Authorization header
    When 客戶端發送 HTTP 請求，header 包含 "Authorization: Basic base64string"
    Then ApiKeyAuthenticator.authenticate(req) 偵測到非 Bearer 格式
    And 回傳 HTTP 401 Unauthorized，body 包含 { error: "Bearer token required" }

  # === Rate Limit ===

  Scenario: 單一 API Key 請求超過 rate limit
    Given ServerConfig.http.rate_limit.per_key = { max: 100, window_ms: 60000 }
    When 同一 API Key 在 60 秒內發送第 101 次請求
    Then RateLimiter.checkLimit(api_key) 偵測到超過 per_key 限制
    And 回傳 HTTP 429 Too Many Requests，body 包含 { error: "Rate limit exceeded" }
    And Response header 包含 Retry-After

  Scenario: 單一 IP 請求超過 rate limit
    Given ServerConfig.http.rate_limit.per_ip = { max: 200, window_ms: 60000 }
    When 同一 IP 在 60 秒內發送第 201 次請求
    Then RateLimiter.checkLimit(client_ip) 偵測到超過 per_ip 限制
    And 回傳 HTTP 429 Too Many Requests

  Scenario: rate limit 時間窗口重置後恢復存取
    Given 同一 API Key 已達到 per_key rate limit 上限
    And 時間窗口（window_ms）過期
    When 該 API Key 再次發送請求
    Then RateLimiter 計數器已重置
    And 請求正常通過 rate limit 檢查

  # === CORS ===

  Scenario: 啟用 CORS 設定供瀏覽器使用
    Given ServerConfig.http.cors.enabled = true
    And ServerConfig.http.cors 設定 allowed_origins, allowed_methods, allowed_headers
    When 瀏覽器發送 preflight OPTIONS 請求
    Then CorsHandler 回傳 HTTP 204，headers 包含：
      | Header                         | 值                                |
      | Access-Control-Allow-Origin    | (依設定的 allowed_origins)        |
      | Access-Control-Allow-Methods   | (依設定的 allowed_methods)        |
      | Access-Control-Allow-Headers   | (依設定的 allowed_headers)        |

  Scenario: 未啟用 CORS 時不回傳 CORS headers
    Given ServerConfig.http.cors.enabled = false 或未設定
    When 瀏覽器發送跨域請求
    Then CorsHandler 不附加任何 CORS headers

  # === 進階認證方案 ===

  Scenario: 支援 JWT / OIDC 認證（企業選項）
    Given ServerConfig.http.auth_scheme = "jwt"
    And 系統已設定 JWT 簽章驗證所需的 public key / JWKS endpoint
    When 客戶端發送 HTTP 請求，header 包含 "Authorization: Bearer <valid-jwt-token>"
    Then JwtAuthenticator.authenticate(req) 驗證 JWT 簽章與 exp 有效期限
    And 驗證通過，請求繼續處理

  Scenario: JWT token 過期被拒絕
    Given ServerConfig.http.auth_scheme = "jwt"
    When 客戶端發送 HTTP 請求，header 包含過期的 JWT token
    Then JwtAuthenticator.authenticate(req) 偵測到 token expired
    And 回傳 HTTP 401 Unauthorized，body 包含 { error: "Token expired" }

  Scenario: 支援 mTLS 認證（內網高安全場景）
    Given ServerConfig.http.auth_scheme = "mtls"
    And HttpTransport 已設定 TLS 憑證驗證
    When 客戶端使用有效的客戶端憑證建立 TLS 連線
    Then TLS handshake 成功，客戶端憑證驗證通過
    And 請求繼續處理

  Scenario: mTLS 認證失敗 - 無效的客戶端憑證
    Given ServerConfig.http.auth_scheme = "mtls"
    When 客戶端使用無效的客戶端憑證建立 TLS 連線
    Then TLS handshake 失敗
    And 連線被拒絕
