# language: zh-TW
# Generated by sa-expert
# Source: pm/mongodb-security.feature
# Project scan date: 2026-03-04

Feature: MongoDB 安全攔截（MongoDB Security）
  對應模組：src/security/MongoValidator.ts
  相關類別：IMongoValidator, MongoValidator
  資料型別：MongoOperation (src/types/query.ts)

  Background:
    Given MCPServer 已啟動
    And MongoValidator 已初始化
    And MongoValidator 允許的操作白名單 = ["find", "aggregate", "countDocuments", "distinct", "listCollections", "listIndexes", "explain"]
    And MongoValidator 禁止的寫入操作 = ["insertOne", "insertMany", "updateOne", "updateMany", "replaceOne", "deleteOne", "deleteMany", "bulkWrite", "findOneAndUpdate", "findOneAndDelete", "findOneAndReplace"]
    And MongoValidator 禁止的管理操作 = ["drop", "dropDatabase", "createCollection", "createIndex", "dropIndex", "renameCollection"]
    And MongoValidator 禁止的 pipeline stage = ["$out", "$merge"]
    And ConnectionManager 已建立 "mongo-db" 的 ConnectionPool（type: mongodb）

  Scenario Outline: 允許的 MongoDB 唯讀操作通過驗證
    When MongoValidator.validateOperation("<操作類型>") 被呼叫
    Then 操作類型存在於白名單中
    And MongoValidator 回傳 { valid: true, operation: "<操作類型>" }

    Examples:
      | 操作類型         |
      | find             |
      | aggregate        |
      | countDocuments   |
      | distinct         |
      | listCollections  |
      | listIndexes      |
      | explain          |

  Scenario Outline: 禁止的 MongoDB 寫入操作被攔截
    When MongoValidator.validateOperation("<操作類型>") 被呼叫
    Then 操作類型存在於寫入操作黑名單中
    And MongoValidator 回傳 { valid: false, operation: "<操作類型>", error: "Write operation <操作類型> is not allowed" }

    Examples:
      | 操作類型              |
      | insertOne             |
      | insertMany            |
      | updateOne             |
      | updateMany            |
      | replaceOne            |
      | deleteOne             |
      | deleteMany            |
      | bulkWrite             |
      | findOneAndUpdate      |
      | findOneAndDelete      |
      | findOneAndReplace     |

  Scenario Outline: 禁止的 MongoDB 破壞性管理操作被攔截
    When MongoValidator.validateOperation("<操作類型>") 被呼叫
    Then 操作類型存在於管理操作黑名單中
    And MongoValidator 回傳 { valid: false, operation: "<操作類型>", error: "Administrative operation <操作類型> is not allowed" }

    Examples:
      | 操作類型           |
      | drop               |
      | dropDatabase       |
      | createCollection   |
      | createIndex        |
      | dropIndex          |
      | renameCollection   |

  Scenario Outline: Aggregate pipeline 包含禁止的 stage 被攔截
    When MongoValidator.validatePipeline(pipeline) 被呼叫，pipeline 包含 "<stage>" stage
    Then MongoValidator 掃描 pipeline 陣列中每個 stage 的 key
    And 檢測到 "<stage>" 存在於禁止的 pipeline stage 清單中
    And MongoValidator 回傳 { valid: false, error: "Pipeline stage <stage> is not allowed: writes data to output collection" }

    Examples:
      | stage   |
      | $out    |
      | $merge  |

  Scenario: Aggregate pipeline 不包含禁止 stage 時通過驗證
    When MongoValidator.validatePipeline(pipeline) 被呼叫，pipeline 僅包含 $match、$group、$sort、$project
    Then MongoValidator 掃描所有 stage，無命中禁止清單
    And MongoValidator 回傳 { valid: true }

  Scenario: 可選限制 $lookup 防止跨庫爆量查詢
    Given ServerConfig 中啟用了 mongo_security.restrict_lookup = true
    When MongoValidator.validatePipeline(pipeline) 被呼叫，pipeline 包含 "$lookup" stage
    Then MongoValidator 根據 restrict_lookup 設定攔截該操作
    And 回傳 { valid: false, error: "$lookup is restricted by server policy" }

  Scenario: 可選限制 $graphLookup 防止跨庫爆量查詢
    Given ServerConfig 中啟用了 mongo_security.restrict_graphLookup = true
    When MongoValidator.validatePipeline(pipeline) 被呼叫，pipeline 包含 "$graphLookup" stage
    Then MongoValidator 根據 restrict_graphLookup 設定攔截該操作
    And 回傳 { valid: false, error: "$graphLookup is restricted by server policy" }

  Scenario: MongoDB 查詢自動套用預設 limit 1000 筆
    When MongoDBQueryTool.execute() 處理 find 操作，input 未指定 limit
    Then MongoDBQueryTool 自動注入 limit = 1000
    And 傳遞給 MongoDBDriver 的 options.limit = 1000

  Scenario: MongoDB 查詢自動套用預設 maxTimeMS 30000
    When MongoDBQueryTool.execute() 處理 find 操作，input 未指定 timeout_ms
    Then MongoDBQueryTool 自動注入 maxTimeMS = 30000
    And 傳遞給 MongoDBDriver 的 options.maxTimeMS = 30000

  Scenario: 雙保險機制 - server policy 攔截寫入操作
    When AI Client 嘗試對 MongoDB 提交 "insertOne" 操作
    Then MongoValidator.validateOperation("insertOne") 在應用層攔截
    And 操作不會被送至 MongoDB 資料庫
    And 回傳安全錯誤訊息

  Scenario: 雙保險機制 - DB RBAC 只讀帳號阻擋漏網寫入
    Given MongoDB 連線使用 RBAC 只讀帳號（read role）
    When 有操作繞過 MongoValidator（理論上不應發生）嘗試寫入
    Then MongoDB 資料庫層面以權限不足拒絕寫入
    And MongoDBDriver 捕獲權限錯誤並回傳給呼叫端
