# language: zh-TW
# Generated by sa-expert
# Source: pm/multi-database-driver.feature
# Project scan date: 2026-03-04

Feature: 多資料庫 Driver 支援（Multi-Database Driver）
  對應模組：src/database/drivers/
  相關類別：IDriverAdapter, DriverFactory, MSSQLDriver, MySQLDriver, PostgreSQLDriver, OracleDriver, MongoDBDriver
  資料型別：QueryResult, ColumnInfo (src/types/query.ts), DatabaseType (src/types/connection.ts)

  Background:
    Given MCPServer 已啟動且 ToolRegistry 已註冊所有 Tools
    And DriverFactory 已初始化

  Scenario Outline: 支援不同類型的資料庫連線
    Given 設定檔中包含類型為 "<資料庫類型>" 的連線，對應 driver 為 "<Driver>"
    When DriverFactory.createDriver("<Driver>") 被呼叫
    Then 回傳對應的 IDriverAdapter 實作類別 "<DriverClass>"
    And 該 IDriverAdapter.connect(config) 成功建立連線
    And 該 IDriverAdapter.execute(query) 回傳 QueryResult 格式：{ columns: ColumnInfo[], rows: Record<string, unknown>[], rowCount: number, truncated: boolean, executionTimeMs: number }

    Examples:
      | 資料庫類型             | Driver   | DriverClass       |
      | Microsoft SQL Server   | mssql    | MSSQLDriver       |
      | MySQL                  | mysql2   | MySQLDriver       |
      | PostgreSQL             | pg       | PostgreSQLDriver  |
      | Oracle                 | oracledb | OracleDriver      |
      | MongoDB                | mongodb  | MongoDBDriver     |

  Scenario: 查詢結果統一輸出格式
    Given AI Client 對任一資料庫的 IDriverAdapter 執行查詢
    When IDriverAdapter.execute(query) 成功執行
    Then 回傳的 QueryResult 物件結構為：
      | 欄位            | 型別                      | 說明                |
      | columns         | ColumnInfo[]              | 欄位名稱與型別陣列  |
      | rows            | Record<string, unknown>[] | 資料列陣列          |
      | rowCount        | number                    | 實際回傳行數        |
      | truncated       | boolean                   | 是否被截斷          |
      | executionTimeMs | number                    | 執行耗時（毫秒）    |
    And ColumnInfo 結構為：{ name: string, type: string }
