# language: zh-TW
# Generated by sa-expert
# Source: pm/schema-discovery.feature
# Project scan date: 2026-03-04

Feature: Schema 探索（Schema Discovery）
  對應模組：src/schema/SchemaService.ts, src/schema/SchemaCache.ts
  相關類別：ISchemaService, SchemaService, SchemaCache, DescribeTablesTool, DiscoverSchemaTool
  資料型別：DescribeTablesInput, TableDescription, DiscoverSchemaInput, SchemaOverview (src/types/schema.ts)

  Background:
    Given MCPServer 已啟動且 ToolRegistry 已註冊所有 Tools
    And ConnectionManager 已建立 "sales-db" 的 ConnectionPool（type: mssql）
    And SchemaCache 已初始化，TTL 預設為 10 分鐘

  # === describe_tables：單表精準查詢 ===

  Scenario: describe_tables 成功回傳單一資料表完整結構
    When AI Client 呼叫 MCP Tool "describe_tables" 並傳入：
      | 參數名稱        | 參數值   | 型別   | 必填 |
      | connection_name | sales-db | string | Y    |
      | table_name      | orders   | string | Y    |
    Then DescribeTablesTool.execute() 呼叫 SchemaService.describeTable(driver, "orders")
    And SchemaService 執行資料庫 metadata 查詢（information_schema 或等效）
    And 回傳 TableDescription 物件，包含：
      | 欄位        | 型別             | 說明                              |
      | tableName   | string           | "orders"                         |
      | columns     | ColumnDetail[]   | name, type, nullable, defaultValue |
      | primaryKey  | string[]         | 主鍵欄位名稱陣列                  |
      | indexes     | IndexInfo[]      | name, columns, unique             |
      | foreignKeys | ForeignKeyInfo[] | column, referencedTable, referencedColumn（可選） |
      | rowEstimate | number           | 預估行數（可選）                  |

  Scenario: describe_tables 支援多次呼叫不同資料表
    When AI Client 依序呼叫 MCP Tool "describe_tables"：
      | 第一次 table_name | 第二次 table_name |
      | orders            | customers         |
    Then 每次呼叫 SchemaService.describeTable() 獨立執行
    And 分別回傳 "orders" 與 "customers" 的 TableDescription
    And 每次為單表 metadata 查詢，執行成本低

  Scenario: describe_tables 查詢不存在的資料表
    When AI Client 呼叫 MCP Tool "describe_tables" 並傳入 table_name = "nonexistent_table"
    Then SchemaService.describeTable() 查詢 metadata 未找到該表
    And Tool 回傳錯誤，訊息包含 "Table 'nonexistent_table' not found"

  # === discover_schema：全庫或子集摘要 ===

  Scenario: discover_schema 成功回傳資料庫結構摘要
    When AI Client 呼叫 MCP Tool "discover_schema" 並傳入：
      | 參數名稱        | 參數值   | 型別   | 必填 |
      | connection_name | sales-db | string | Y    |
    Then DiscoverSchemaTool.execute() 先檢查 SchemaCache.get(cacheKey)
    And 若快取未命中，呼叫 SchemaService.discover(driver, options)
    And 回傳 SchemaOverview 物件，包含：
      | 欄位          | 型別              | 說明                                    |
      | database      | string            | 資料庫名稱                              |
      | tables        | TableSummary[]    | 每表包含 name 與 columns（name + type） |
      | relationships | RelationshipInfo[] | FK 或命名推測的關聯（可選）            |
      | truncated     | boolean           | 是否被截斷                              |

  Scenario: discover_schema 使用 include_patterns 篩選
    When AI Client 呼叫 MCP Tool "discover_schema" 並傳入：
      | 參數名稱         | 參數值   | 型別   |
      | connection_name  | sales-db | string |
      | include_patterns | order*   | string |
    Then SchemaService.discover() 使用 glob matching 篩選表名
    And 僅回傳符合 "order*" 模式的資料表（如 orders, order_items）
    And 不回傳不符合模式的資料表

  Scenario: discover_schema 使用 exclude_patterns 排除
    When AI Client 呼叫 MCP Tool "discover_schema" 並傳入：
      | 參數名稱         | 參數值       | 型別   |
      | connection_name  | sales-db     | string |
      | exclude_patterns | tmp_*,log_*  | string |
    Then SchemaService.discover() 排除表名符合 "tmp_*" 或 "log_*" 的資料表
    And 回傳其餘資料表的結構摘要

  Scenario: discover_schema 使用 depth 參數控制探索深度
    When AI Client 呼叫 MCP Tool "discover_schema" 並傳入：
      | 參數名稱        | 參數值   | 型別   |
      | connection_name | sales-db | string |
      | depth           | 1        | number |
    Then SchemaService.discover() 根據 depth 控制回傳層級
    And depth=1 僅回傳 table name 清單，不含欄位詳情

  Scenario: discover_schema 結果從快取命中
    Given AI Client 5 分鐘前已呼叫 discover_schema（connection_name="sales-db"，無篩選）
    And SchemaCache TTL = 10 分鐘
    And SchemaCache 中存在有效快取
    When AI Client 再次呼叫 MCP Tool "discover_schema"（相同參數）
    Then SchemaCache.get(cacheKey) 命中快取
    And 直接回傳快取中的 SchemaOverview
    And 不執行資料庫 metadata 查詢

  Scenario: discover_schema 快取過期後重新查詢
    Given AI Client 15 分鐘前已呼叫 discover_schema（connection_name="sales-db"）
    And SchemaCache TTL = 10 分鐘
    And 快取已過期
    When AI Client 再次呼叫 MCP Tool "discover_schema"（相同參數）
    Then SchemaCache.get(cacheKey) 未命中（expired）
    And SchemaService.discover() 重新查詢資料庫 metadata
    And SchemaCache.set(cacheKey, result, TTL) 更新快取

  Scenario: discover_schema 輸出大小超過限制時截斷
    Given 資料庫包含大量資料表（如 500+ tables）
    When AI Client 呼叫 MCP Tool "discover_schema" 且未傳入篩選條件
    Then SchemaService.discover() 檢測序列化結果大小
    And 若超過最大輸出限制，截斷 tables 清單
    And SchemaOverview.truncated = true
    And 回傳訊息提示使用 include_patterns 縮小範圍
