# language: zh-TW
# Generated by sa-expert
# Source: pm/server-startup.feature
# Project scan date: 2026-03-04

Feature: 伺服器啟動（Server Startup）
  對應模組：src/server/MCPServer.ts, src/config/ConfigLoader.ts
  相關類別：MCPServer, ToolRegistry, ConnectionManager, ConfigLoader

  Background:
    Given 系統已建置 mcp-database-server 專案
    And 存在有效的 YAML 設定檔 "config/default.yaml"，內容包含：
      | 設定區塊     | 必要欄位                              |
      | connections  | name, type, host, port, database      |
      | pool         | max, min, idleTimeout                 |
      | limits       | max_rows, timeout                     |
      | audit        | enabled                               |

  Scenario: 以 CLI/MCP 模式啟動 - 完整初始化流程
    Given YAML 設定檔路徑為 "config/default.yaml"
    When 使用者執行 CLI 命令 "mcp-database-server"
    Then ConfigLoader.loadConfig() 成功載入設定檔並回傳 ServerConfig 物件
    And CredentialResolver.resolve() 為每個 connection 解析 credential
    And ToolRegistry.registerTools() 註冊以下 5 個 MCP Tools：
      | Tool Name        | 對應類別               | 說明           |
      | list_connections | ListConnectionsTool    | 列出資料庫     |
      | describe_tables  | DescribeTablesTool     | 查詢資料表     |
      | query_database   | QueryDatabaseTool      | SQL 查詢       |
      | mongodb_query    | MongoDBQueryTool       | MongoDB 查詢   |
      | discover_schema  | DiscoverSchemaTool     | Schema 探索    |
    And ConnectionManager.createPools() 為所有設定的資料庫建立 ConnectionPool
    And MCPServer.start() 以 StdioTransport 模式啟動
    And Server 狀態為 "running"，transport 為 "stdio"

  Scenario: CLI/MCP 模式不需要 HTTP 認證但仍執行安全策略
    Given MCPServer 已以 StdioTransport 模式啟動
    When AI Client 透過 MCP Protocol（JSON-RPC over STDIO）呼叫任意 Tool
    Then 系統不檢查 Authorization header（STDIO 模式無 HTTP 層）
    And SQLValidator.validate() 仍對 SQL 查詢執行安全驗證
    And QueryPolicy.clampLimits() 仍對查詢參數執行限制夾制
    And AuditLogger.log() 仍在 audit.enabled=true 時記錄稽核日誌

  Scenario: 以 HTTP Server 模式啟動（預設綁定 127.0.0.1）
    Given YAML 設定檔路徑為 "config/default.yaml"
    And 設定檔包含 http.api_keys 至少一組有效 API Key
    When 使用者執行 CLI 命令 "mcp-database-server --http --port 3000"
    Then ConfigLoader.loadConfig() 成功載入設定檔
    And ToolRegistry.registerTools() 註冊所有 MCP Tools
    And ConnectionManager.createPools() 建立所有連線池
    And MCPServer.start() 以 HttpTransport 模式啟動
    And HttpTransport 監聽 port 3000
    And HttpTransport 綁定地址為 "127.0.0.1"（預設值）

  Scenario: 以 HTTP Server 模式啟動並明確綁定所有介面
    Given YAML 設定檔路徑為 "config/default.yaml"
    When 使用者執行 CLI 命令 "mcp-database-server --http --port 3000 --bind 0.0.0.0"
    Then HttpTransport 監聽 port 3000
    And HttpTransport 綁定地址為 "0.0.0.0"，對所有網路介面開放

  Scenario: MCP Tools 註冊完整性驗證
    Given MCPServer 啟動流程已完成
    When 呼叫 ToolRegistry.getRegisteredTools() 取得已註冊 Tool 清單
    Then 回傳的 Tool 清單長度為 5
    And 每個 Tool 具備 name、description、inputSchema 屬性
    And 以下 5 個 Tools 已註冊且可被 MCP Protocol 呼叫：
      | Tool Name        | inputSchema 必填欄位                        |
      | list_connections | (無)                                        |
      | describe_tables  | connection_name, table_name                 |
      | query_database   | connection_name, query                      |
      | mongodb_query    | connection_name, collection, filter         |
      | discover_schema  | connection_name                             |
