# language: zh-TW
# Generated by sa-expert
# Source: pm/sql-query-execution.feature
# Project scan date: 2026-03-04

Feature: SQL 查詢執行（Query Execution）
  對應模組：src/tools/QueryDatabaseTool.ts, src/tools/MongoDBQueryTool.ts
  相關類別：QueryDatabaseTool, MongoDBQueryTool, SQLValidator, MongoValidator, AuditLogger, ConnectionManager
  資料型別：QueryDatabaseInput, MongoDBQueryInput, QueryResult (src/types/query.ts), AuditLogEntry (src/types/audit.ts)

  Background:
    Given MCPServer 已啟動且 ToolRegistry 已註冊所有 Tools
    And ConnectionManager 已建立 "sales-db" 的 ConnectionPool（type: mssql）
    And ServerConfig.limits = { max_rows: 1000, timeout: 30, result_size: 5, max_execution_time: 60 }
    And ServerConfig.audit.enabled = true

  # === SQL 查詢 ===

  Scenario: 成功執行 SELECT 查詢
    Given ConnectionManager.resolveConnection("sales-db") 回傳有效的 MSSQLDriver
    When AI Client 呼叫 MCP Tool "query_database" 並傳入：
      | 參數名稱        | 參數值                   | 型別   | 必填 |
      | connection_name | sales-db                 | string | Y    |
      | query           | SELECT * FROM orders     | string | Y    |
    Then SQLValidator.validate("SELECT * FROM orders") 回傳 SQLValidationPassed
    And QueryPolicy.clampLimits() 套用 server 預設限制
    And MSSQLDriver.execute("SELECT * FROM orders", options) 回傳 QueryResult
    And QueryResult.columns 為 ColumnInfo[] 陣列
    And QueryResult.rows 為 Record<string, unknown>[] 陣列
    And AuditLogger.log() 寫入 AuditLogEntry：
      | 欄位             | 值                       |
      | connection_name  | sales-db                 |
      | query            | SELECT * FROM orders     |
      | row_count        | (實際行數)               |
      | execution_time   | (實際耗時)               |

  Scenario: 成功執行 SHOW 語句
    When AI Client 呼叫 MCP Tool "query_database" 並傳入：
      | 參數名稱        | 參數值       | 型別   |
      | connection_name | sales-db     | string |
      | query           | SHOW TABLES  | string |
    Then SQLValidator.validate("SHOW TABLES") 回傳 SQLValidationPassed
    And Driver 成功執行查詢並回傳 QueryResult

  Scenario: 成功執行 DESCRIBE 語句
    When AI Client 呼叫 MCP Tool "query_database" 並傳入：
      | 參數名稱        | 參數值           | 型別   |
      | connection_name | sales-db         | string |
      | query           | DESCRIBE orders  | string |
    Then SQLValidator.validate("DESCRIBE orders") 回傳 SQLValidationPassed
    And Driver 成功執行查詢並回傳 QueryResult

  Scenario: 成功執行 EXPLAIN 語句
    When AI Client 呼叫 MCP Tool "query_database" 並傳入：
      | 參數名稱        | 參數值                          | 型別   |
      | connection_name | sales-db                        | string |
      | query           | EXPLAIN SELECT * FROM orders    | string |
    Then SQLValidator.validate("EXPLAIN SELECT * FROM orders") 回傳 SQLValidationPassed
    And Driver 成功執行查詢並回傳 QueryResult

  Scenario: 查詢結果超過 max_rows 限制時截斷回傳
    Given ServerConfig.limits.max_rows = 1000
    When AI Client 呼叫 MCP Tool "query_database"，查詢結果原始行數超過 1000 筆
    Then QueryDatabaseTool 截斷結果至前 1000 筆
    And QueryResult.truncated = true
    And QueryResult.rowCount = 1000

  Scenario: 查詢結果超過 result size 限制時截斷回傳
    Given ServerConfig.limits.result_size = 5（MB）
    When AI Client 呼叫 MCP Tool "query_database"，查詢結果序列化後超過 5MB
    Then QueryDatabaseTool 截斷結果至 5MB 以內
    And QueryResult.truncated = true

  Scenario: 查詢執行超過 timeout 限制
    Given ServerConfig.limits.timeout = 30（秒）
    When AI Client 呼叫 MCP Tool "query_database"，SQL 執行超過 30 秒
    Then Driver 在 30 秒後中止查詢（query cancellation）
    And Tool 回傳錯誤，訊息包含 "query timeout exceeded"

  Scenario: 查詢執行超過 max execution time 限制
    Given ServerConfig.limits.max_execution_time = 60（秒）
    When AI Client 呼叫 MCP Tool "query_database"，SQL 執行超過 60 秒
    Then 系統強制中止查詢
    And Tool 回傳錯誤，訊息包含 "max execution time exceeded"

  # === MongoDB 查詢 ===

  Scenario: 成功執行 MongoDB find 查詢
    Given ConnectionManager 已建立 "mongo-db" 的 ConnectionPool（type: mongodb）
    And ConnectionManager.resolveConnection("mongo-db") 回傳有效的 MongoDBDriver
    When AI Client 呼叫 MCP Tool "mongodb_query" 並傳入：
      | 參數名稱        | 參數值              | 型別   | 必填 |
      | connection_name | mongo-db            | string | Y    |
      | collection      | orders              | string | Y    |
      | filter          | { "status": "active" } | object | Y |
    Then MongoValidator.validateOperation("find") 回傳 MongoValidationPassed
    And MongoDBDriver 執行 find 操作並回傳 QueryResult
    And AuditLogger.log() 寫入 AuditLogEntry

  Scenario: MongoDB 查詢套用預設 limit 1000 筆
    Given ConnectionManager 已建立 "mongo-db" 的 ConnectionPool（type: mongodb）
    When AI Client 呼叫 MCP Tool "mongodb_query" 但未傳入 limit 參數
    Then MongoDBQueryTool 自動套用 limit = 1000
    And 查詢結果最多回傳 1000 筆文件

  Scenario: MongoDB 查詢套用預設 maxTimeMS 30000
    Given ConnectionManager 已建立 "mongo-db" 的 ConnectionPool（type: mongodb）
    When AI Client 呼叫 MCP Tool "mongodb_query" 但未傳入 timeout_ms 參數
    Then MongoDBQueryTool 自動套用 maxTimeMS = 30000
    And 查詢超過 30 秒後自動中止
