# language: zh-TW
# Generated by sa-expert
# Source: pm/sql-security.feature
# Project scan date: 2026-03-04

Feature: SQL 安全驗證（SQL Security）
  對應模組：src/security/SQLValidator.ts
  相關類別：ISQLValidator, SQLValidator
  依賴套件：node-sql-parser（SQL 語句解析）

  Background:
    Given MCPServer 已啟動
    And SQLValidator 已初始化（內部持有 node-sql-parser 實例）
    And SQLValidator 白名單語句類型 = ["SELECT", "SHOW", "DESCRIBE", "EXPLAIN"]
    And SQLValidator 黑名單語句類型 = ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE"]

  Scenario Outline: 允許的 SQL 語句類型通過驗證
    When SQLValidator.validate("<SQL語句>") 被呼叫
    Then node-sql-parser 解析語句類型為 "<語句類型>"
    And 語句類型存在於白名單中
    And SQLValidator 回傳 { valid: true, statementType: "<語句類型>" }

    Examples:
      | 語句類型 | SQL語句                          |
      | SELECT   | SELECT * FROM orders             |
      | SHOW     | SHOW TABLES                      |
      | DESCRIBE | DESCRIBE orders                  |
      | EXPLAIN  | EXPLAIN SELECT * FROM orders     |

  Scenario Outline: 禁止的 SQL 語句類型被攔截
    When SQLValidator.validate("<SQL語句>") 被呼叫
    Then node-sql-parser 解析語句類型為 "<語句類型>"
    And 語句類型存在於黑名單中
    And SQLValidator 回傳 { valid: false, statementType: "<語句類型>", error: "Statement type <語句類型> is not allowed" }

    Examples:
      | 語句類型 | SQL語句                                    |
      | INSERT   | INSERT INTO orders VALUES (1, 'test')      |
      | UPDATE   | UPDATE orders SET status = 'cancelled'     |
      | DELETE   | DELETE FROM orders WHERE id = 1            |
      | DROP     | DROP TABLE orders                          |
      | ALTER    | ALTER TABLE orders ADD COLUMN note TEXT     |
      | TRUNCATE | TRUNCATE TABLE orders                      |

  Scenario: SQL Injection 攻擊被攔截
    When SQLValidator.validate("SELECT * FROM orders; DROP TABLE orders;--") 被呼叫
    Then node-sql-parser 檢測到多語句（multi-statement）或注入特徵
    And SQLValidator 回傳 { valid: false, error: "SQL injection detected" }

  Scenario: Read Only 強制執行
    When SQLValidator.validate() 被呼叫，傳入任何包含資料修改意圖的 SQL
    Then SQLValidator 檢測語句類型不在白名單中
    And 回傳驗證失敗，確保唯讀模式強制執行
